CREATE SCHEMA IF NOT EXISTS couponvalidator;

CREATE TABLE couponvalidator.campaign
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     VARCHAR(255) not null,
    start_date               TIMESTAMPTZ  not null,
    end_date                 TIMESTAMPTZ  not null,
    coupon_code              VARCHAR(10)  not null,
    max_redemptions          INT          not null,
    redemption_count         INT          not null,
    per_customer_redemptions SMALLINT     not null,
    discount_percentage      SMALLINT     not null
);

CREATE TABLE couponvalidator.coupon_redemption
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    redeemed_at         TIMESTAMPTZ    not null,
    customer_id         BIGINT         not null,
    expires_at          TIMESTAMPTZ    not null,
    redeem_confirmed    BOOLEAN DEFAULT FALSE,
    original_amount     numeric(12, 2) not null,
    discounted_amount   numeric(12, 2) not null,
    discount_percentage SMALLINT       not null,
    campaign_id         BIGINT references couponvalidator.campaign (id)
);

CREATE INDEX idx_coupon_code ON couponvalidator.campaign (coupon_code);